# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "pimcommon"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/pimcommon"

[[annotations]]
path = ["src/pimcommonautocorrection/autocorrection/autotests/data/acor_fr.dat", "src/pimcommonautocorrection/autocorrection/autotests/data/**.xml", "src/pimcommontexttranslator/translator/DEBUG", "src/pimcommon/widgets/icons/hint.svg", "src/pimcommon/widgets/icons/visibility.svg", "src/pimcommontextgrammarcheck/grammalecte/autotests/data/**.json", "src/pimcommontextgrammarcheck/languagetool/autotests/data/**.json", "src/pimcommon/needupdateversion/autotests/data/*.html", ".gersemirc", "src/pimcommon/pimcommon-index.qdoc", "src/pimcommon/pimcommon.qdoc", "src/pimcommon/pimcommon.qdocconf", "src/pimcommon-activities/pimcommon-activities.qdoc", "src/pimcommon-activities/pimcommon-activities.qdocconf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
